"""add assigned engineer details

Revision ID: f1bf460a89e7
Revises: 8a167f40e271
Create Date: 2026-07-22 17:24:23.537403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bf460a89e7'
down_revision: Union[str, Sequence[str], None] = '8a167f40e271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_to_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assigned_to_email')
    # ### end Alembic commands ###
